#!/bin/bash

# todo automate the following comment
# Changes to the pre-commit hook will apply only after running `yarn install`

set -e

# list all staged files
output=$(git diff --name-only --cached)

if [[ $output =~ .*"deal-no-deal-backend"*.*\.ts ]]; then
  # DND project
  cd deal-no-deal-backend || exit

  yarn tsc --noEmit

  yarn lint

  yarn test

  yarn test:e2e

  cd ..
fi
