version: '3.9'

services:
  mongo1:
    image: mongo:4.4
    container_name: mongo1
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TF_VAR_COGNITO_DEFAULT_USER_NAME: ${TF_VAR_COGNITO_DEFAULT_USER_NAME}
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      - MONGO
    restart: always
    volumes:
      - type: volume
        source: MONGO_DATA1
        target: /data/db
#      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
#      - ./init-mongo.sh:/scripts/init-mongo.sh
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo2:
    image: mongo:4.4
    container_name: mongo2
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TF_VAR_COGNITO_DEFAULT_USER_NAME: ${TF_VAR_COGNITO_DEFAULT_USER_NAME}
    networks:
      - MONGO
    ports:
      - "27018:27017"
    expose:
      - 27017
    restart: always
    volumes:
      - type: volume
        source: MONGO_DATA2
        target: /data/db
#      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo3:
    image: mongo:4.4
    container_name: mongo3
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TF_VAR_COGNITO_DEFAULT_USER_NAME: ${TF_VAR_COGNITO_DEFAULT_USER_NAME}
    networks:
      - MONGO
    ports:
      - "27019:27017"
    expose:
      - 27017
    restart: always
    volumes:
      - type: volume
        source: MONGO_DATA3
        target: /data/db
    #      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./init-mongo.sh:/scripts/init-mongo.sh
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: 0.0.0.0
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo1
    networks:
      - MONGO

networks:
  MONGO:
    name: MONGO
    driver: bridge

volumes:
  MONGO_DATA1:
    name: MONGO_DATA1
  MONGO_DATA2:
    name: MONGO_DATA2
  MONGO_DATA3:
    name: MONGO_DATA3
