#!/bin/bash

set -e

# list all staged files
output=$(git diff --name-only --cached)

if [[ $output =~ .*"deal-no-deal-backend"*. ]]; then
  # DND project
  cd deal-no-deal-backend || exit

  yarn tsc --noEmit

  yarn lint

  yarn test

  cd ..
fi


