version: '3.9'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo-container
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TF_VAR_COGNITO_DEFAULT_USER_NAME: ${TF_VAR_COGNITO_DEFAULT_USER_NAME}
    networks:
      - mongo-network
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - type: volume
        source: MONGO_DATA3
        target: /data/db
      - ./scripts/init-mongo.sh:/scripts/init-mongo.sh
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo-ilya:
    image: mongo:4.4
    container_name: mongo-ilya
    networks:
      - mongo-network
    ports:
      - "3001:27017"
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env

  webapp:
    build: .
    container_name: webapp
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env
      - ./src:/app/src
    depends_on:
      - mongo
    networks:
      - mongo-network
    env_file:
      - .env
    command:
      - ./scripts/start-webapp.sh

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo-container:27017/?replicaSet=dbrs"
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    name: MONGO
    driver: bridge

volumes:
  MONGO_DATA1:
    name: MONGO_DATA1
  MONGO_DATA2:
    name: MONGO_DATA2
  MONGO_DATA3:
    name: MONGO_DATA3
