name: Cypress Tests

on: [ push ]

defaults:
  run:
    working-directory: ./meal-tracker

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: ./meal-tracker
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          working-directory: ./meal-tracker

